const LANGUAGES = [
  { code: 'ru', label: 'Русский', flag: '🇷🇺' },
  { code: 'kg', label: 'Кыргызча', flag: '🇰🇬' },
  { code: 'en', label: 'English', flag: '🇺🇸' }
];

const LANGS = {
  ru: {
    // ─── Navigation ───
    'nav.home': 'Главная',
    'nav.create': 'Создать',
    'nav.favorites': 'Избранное',
    'nav.chat': 'Чаты',
    'nav.profile': 'Профиль',

    // ─── Theme ───
    'theme.light': 'Светлая тема',
    'theme.dark': 'Тёмная тема',
    'theme.light.aria': 'Включить светлую тему',
    'theme.dark.aria': 'Включить тёмную тему',

    // ─── Auth ───
    'auth.login': 'Войти',
    'auth.logout': 'Выйти',
    'auth.register': 'Регистрация',
    'auth.welcome': 'Добро пожаловать!',
    'auth.welcome.sub': 'Войдите или создайте аккаунт',
    'auth.login.tab': 'Войти',
    'auth.register.tab': 'Регистрация',
    'auth.username': 'Никнейм',
    'auth.password': 'Пароль',
    'auth.confirm': 'Повторите пароль',
    'auth.login.btn': 'Войти 🚀',
    'auth.register.btn': 'Зарегистрироваться 🚀',
    'auth.fill.all': 'Заполните все поля',
    'auth.username.len': 'Никнейм от 2 до 20 символов',
    'auth.password.len': 'Пароль минимум 6 символов',
    'auth.password.match': 'Пароли не совпадают',
    'auth.taken': 'Этот никнейм уже занят',
    'auth.register.error': 'Ошибка регистрации',
    'auth.notfound': 'Пользователь не найден',
    'auth.wrongpass': 'Неверный пароль',
    'auth.loggedout': 'Вы вышли из аккаунта',
    'auth.logout.confirm.title': 'Выйти из аккаунта?',
    'auth.logout.confirm.sub': 'Вы уверены, что хотите выйти?',
    'auth.logout.confirm.ok': '🚪 Выйти',
    'auth.logout.confirm.cancel': 'Отмена',
    'auth.strength.weak': 'Слабый',
    'auth.strength.medium': 'Средний',
    'auth.strength.strong': 'Надёжный',

    // ─── Search / Filters ───
    'search.placeholder': 'Искать объявления...',
    'search.clear': 'Очистить',
    'filter.all': 'Все',
    'filter.sort': 'Сортировка:',
    'filter.newest': 'Сначала новые',
    'filter.oldest': 'Сначала старые',
    'filter.price.asc': 'Цена ↑',
    'filter.price.desc': 'Цена ↓',
    'filter.popular': 'По просмотрам',
    'filter.my': 'Мои',
    'filter.my.title': 'Показать только мои объявления',
    'filter.price.from': 'Цена от',
    'filter.price.to': 'Цена до',
    'filter.reset': 'Сбросить',
    'filter.reset.title': 'Сбросить все фильтры',

    // ─── Item Card ───
    'item.fav.add': 'Добавлено в избранное',
    'item.fav.remove': 'Удалено из избранного',
    'item.fav.add.title': 'В избранное',
    'item.fav.remove.title': 'Убрать из избранного',
    'item.sold': 'Продано',
    'item.free': 'Бесплатно',
    'item.currency': 'Сом',
    'item.no.description': 'Без описания',
    'item.no.contact': 'Не указан',
    'item.views': 'просмотров',
    'item.seller': 'Продавец',
    'item.contact': '📩 Связаться',
    'item.description': 'Описание',
    'item.edit': '✏️ Редактировать',
    'item.delete': '🗑 Удалить',
    'item.restore': '♻️ Восстановить',
    'item.sold.toggle': '✅ Продано',
    'item.sold.untoggle': '↩️ Вернуть в продажу',
    'item.share.copy': 'Ссылка скопирована! 🔗',
    'item.share.tg': 'Поделиться в Telegram',
    'item.share.wa': 'Поделиться в WhatsApp',

    // ─── Item Detail ───
    'detail.loading': 'Загрузка объявления...',
    'detail.notfound': 'Объявление не найдено',
    'detail.notfound.text': 'Возможно, оно было удалено',
    'detail.back': '← На главную',
    'detail.breadcrumb': 'Главная',
    'detail.recent': '👁 Недавно вы смотрели',
    'detail.similar': '📂 Похожие объявления',

    // ─── Create / Edit ───
    'create.title.new': '✨ Новое объявление',
    'create.title.edit': '✏️ Редактирование',
    'create.sub.new': 'Заполните форму, чтобы разместить товар',
    'create.sub.edit': 'Измените данные объявления',
    'create.breadcrumb.new': 'Новое объявление',
    'create.breadcrumb.edit': 'Редактирование',
    'create.btn.publish': '🚀 Опубликовать',
    'create.btn.save': '💾 Сохранить изменения',
    'create.btn.back': '← Назад',
    'create.label.photo': '📷 Фото товара',
    'create.upload.text': 'Нажмите или перетащите фото',
    'create.upload.hint': 'JPG, PNG до 2 MB',
    'create.upload.remove': 'Удалить фото',
    'create.label.title': 'Название',
    'create.title.placeholder': 'Например: iPhone 12 чехол',
    'create.title.hint': 'До 100 символов',
    'create.label.desc': 'Описание',
    'create.desc.placeholder': 'Опишите товар подробнее: состояние, размер, цвет...',
    'create.desc.hint': 'До 5000 символов',
    'create.label.price': 'Цена',
    'create.price.placeholder': '0 = бесплатно',
    'create.price.hint': 'Введите 0, если отдаёте бесплатно',
    'create.label.category': 'Категория',
    'create.category.placeholder': 'Выберите категорию',
    'create.label.contact': 'Контакт',
    'create.contact.placeholder': 'Telegram, WhatsApp или номер телефона',
    'create.error.title': 'Введите название товара',
    'create.error.desc': 'Добавьте описание',
    'create.error.price': 'Укажите цену',
    'create.error.category': 'Выберите категорию',
    'create.error.contact': 'Укажите контакт для связи',
    'create.error.image': 'Выберите изображение (JPG, PNG)',
    'create.error.filesize': 'Файл слишком большой (макс. 2 MB)',
    'create.error.notfound': 'Объявление не найдено',
    'create.error.permission': 'Вы не можете редактировать это объявление',
    'create.loading.photo': '⏳ Загрузка фото...',
    'create.loading.save': '⏳ Сохранение...',
    'create.success.update': 'Объявление обновлено! ✅',
    'create.success.create': 'Объявление создано! 🎉',
    'create.error.save': 'Ошибка сохранения',

    // ─── Profile ───
    'profile.edit': '✏️ Редактировать',
    'profile.logout': '🚪 Выйти',
    'profile.myitems': 'Мои объявления',
    'profile.tab.active': 'Активные',
    'profile.tab.deleted': 'Удалённые',
    'profile.loading': 'Загрузка объявлений...',
    'profile.modal.title': 'Редактировать профиль',
    'profile.modal.sub': 'Заполните информацию о себе',
    'profile.label.avatar': 'Фото профиля',
    'profile.avatar.upload': '📷 Загрузить',
    'profile.avatar.remove': '✕ Удалить',
    'profile.label.name': 'Имя',
    'profile.name.placeholder': 'Иван Иванов',
    'profile.label.email': 'Email',
    'profile.email.placeholder': 'your@school.edu',
    'profile.label.bio': 'О себе',
    'profile.bio.placeholder': 'Расскажите о себе, увлечениях, контактах...',
    'profile.label.location': 'Город / Школа',
    'profile.location.placeholder': 'Например: Бишкек, Школа №70',
    'profile.cancel': 'Отмена',
    'profile.save': '💾 Сохранить',
    'profile.no.email': 'Email не указан',
    'profile.member.since': 'Участник с 2026 года',
    'profile.empty.title': 'У вас пока нет объявлений',
    'profile.empty.text': 'Создайте своё первое объявление',
    'profile.empty.btn': 'Создать объявление',
    'profile.empty.deleted': 'Нет удалённых объявлений',
    'profile.empty.deleted.text': 'Удалённые объявления будут здесь',
    'profile.avatar.error': 'Фото не больше 2 MB',
    'profile.saved': 'Профиль обновлён',

    // ─── Chat ───
    'chat.title': 'Сообщения',
    'chat.loading': 'Загрузка...',
    'chat.select': 'Выберите чат',
    'chat.select.text': 'Нажмите на диалог слева, чтобы просмотреть сообщения',
    'chat.no.conversations': 'Нет диалогов',
    'chat.no.messages': 'Нет сообщений',
    'chat.input.placeholder': 'Напишите сообщение...',
    'chat.send': 'Отправить',
    'detail.chat': '💬 Написать в чат',

    // ─── Favorites ───
    'fav.title': '♥ Избранное',
    'fav.subtitle': 'Ваши сохранённые объявления',
    'fav.empty.title': 'Избранного пока нет',
    'fav.empty.text': 'Добавляйте объявления в избранное, чтобы не потерять',
    'fav.empty.btn': '← На главную',

    // ─── Empty States ───
    'empty.notfound': 'Ничего не найдено',
    'empty.notfound.text': 'Попробуйте изменить поиск или фильтры',
    'empty.noitems': 'Объявлений пока нет',
    'empty.noitems.text': 'Будьте первым, кто разместит объявление!',
    'empty.create': 'Создать объявление',

    // ─── Hero ───
    'hero.title': 'Добро пожаловать в',
    'hero.sub': 'Покупай, продавай и обменивай вещи с одноклассниками. Учебники, гаджеты, одежда и многое другое!',
    'hero.cta': 'Разместить объявление',

    // ─── Breadcrumbs ───
    'breadcrumb.home': 'Главная',

    // ─── Footer ───
    'footer.text': '🎒 School Shop © 2026 — Создано с ❤️',
    'footer.export': '💾 Экспорт',
    'footer.export.title': 'Скачать резервную копию',

    // ─── Scroll ───
    'scroll.top': 'Наверх',

    // ─── Time ───
    'time.justnow': 'Только что',
    'time.minutes': 'мин. назад',
    'time.hours': 'ч. назад',
    'time.days': 'дн. назад',

    // ─── Validation ───
    'validate.title.len': 'Название должно быть минимум 3 символа',
    'validate.desc.len': 'Описание не может быть длиннее 5000 символов',

    // ─── Delete Modal ───
    'delete.title': 'Удалить объявление?',
    'delete.sub': 'Объявление можно будет восстановить',
    'delete.cancel': 'Отмена',
    'delete.confirm': '🗑 Удалить',

    // ─── Toasts ───
    'toast.copied': 'Ссылка скопирована! 🔗',
    'toast.deleted': 'Объявление скрыто. Его можно восстановить ♻️',
    'toast.restored': 'Объявление восстановлено! ✅',
    'toast.sold': '✅ Объявление помечено как проданное',
    'toast.active': '↩️ Объявление снова в продаже',
    'toast.load.error': 'Ошибка загрузки данных',
    'toast.save.error': 'Ошибка сохранения данных',
    'toast.version.error': 'Конфликт версий — обновите страницу',
    'toast.photo.error': 'Ошибка загрузки фото',
    'toast.update.error': 'Ошибка обновления',
    'toast.delete.error': 'Ошибка удаления',
    'toast.restore.error': 'Ошибка восстановления',
    'toast.status.error': 'Ошибка обновления статуса',
    'toast.create.error': 'Ошибка создания объявления',

    // ─── Items count ───
    'items.one': 'объявление',
    'items.few': 'объявления',
    'items.many': 'объявлений',
    'items.found': 'Найдено',
    'items.found.end': '',
    'items.loading': 'Загрузка...',

    // ─── Categories ───
    'cat.учебники': 'Учебники',
    'cat.электроника': 'Электроника',
    'cat.одежда': 'Одежда',
    'cat.другое': 'Другое',

    // ─── Language Selector ───
    'lang.ru': 'Русский',
    'lang.kg': 'Кыргызча',
    'lang.en': 'English',

    // ─── Aliases / Extra keys ───
    'nav.logout': 'Выйти',
    'nav.back': '← Назад',
    'auth.subtitle': 'Войдите или создайте аккаунт',
    'auth.password.confirm': 'Повторите пароль',
    'filter.myads': 'Мои',
    'sort.newest': 'Сначала новые',
    'sort.oldest': 'Сначала старые',
    'sort.price.asc': 'Цена ↑',
    'sort.price.desc': 'Цена ↓',
    'sort.views': 'По просмотрам',
    'footer.made': 'Создано с ❤️',
    'hero.welcome': 'Добро пожаловать в',
    'hero.subtitle': 'Покупай, продавай и обменивай вещи с одноклассниками. Учебники, гаджеты, одежда и многое другое!',
    'favorites.subtitle': 'Ваши сохранённые объявления',
    'favorites.empty.title': 'Избранного пока нет',
    'favorites.empty.text': 'Добавляйте объявления в избранное, чтобы не потерять',
    'detail.breadcrumb': 'Объявление',
    'detail.description': 'Описание',
    'detail.seller': 'Продавец',
    'detail.contact': '📩 Связаться',
    'detail.views': 'просмотров',
    'detail.recently': '👁 Недавно вы смотрели',
    'detail.share.link': 'Копировать ссылку',
    'detail.share.tg': 'Поделиться в Telegram',
    'detail.share.wa': 'Поделиться в WhatsApp',
    'detail.delete.title': 'Удалить объявление?',
    'detail.delete.sub': 'Объявление можно будет восстановить',
    'item.image.alt': 'Фото товара',
    'create.new': 'Новое объявление',
    'create.photo.label': '📷 Фото товара',
    'create.photo.click': 'Нажмите',
    'create.photo.drag': 'или перетащите фото',
    'create.photo.hint': 'JPG, PNG до 2 MB',
    'create.photo.remove': 'Удалить фото',
    'create.title.label': 'Название',
    'create.title.error': 'Введите название товара',
    'create.desc.label': 'Описание',
    'create.desc.error': 'Добавьте описание',
    'create.price.label': 'Цена',
    'create.price.error': 'Укажите цену',
    'create.cat.label': 'Категория',
    'create.cat.error': 'Выберите категорию',
    'create.cat.placeholder': 'Выберите категорию',
    'create.contact.label': 'Контакт',
    'create.contact.error': 'Укажите контакт для связи',
    'create.btn.submit': '🚀 Опубликовать',
    'profile.edit.title': 'Редактировать профиль',
    'profile.edit.sub': 'Заполните информацию о себе',
    'profile.edit.avatar': 'Фото профиля',
    'profile.edit.upload': '📷 Загрузить',
    'profile.edit.remove': '✕ Удалить',
    'profile.edit.name': 'Имя',
    'profile.edit.name.placeholder': 'Иван Иванов',
    'profile.edit.email': 'Email',
    'profile.edit.email.placeholder': 'your@school.edu',
    'profile.edit.bio': 'О себе',
    'profile.edit.bio.placeholder': 'Расскажите о себе, увлечениях, контактах...',
    'profile.edit.location': 'Город / Школа',
    'profile.edit.location.placeholder': 'Например: Бишкек, Школа №70',
    'profile.edit.save': '💾 Сохранить',
    'profile.edit.username': 'Логин',
  },

  kg: {
    'nav.home': 'Башкы',
    'nav.create': 'Жарыялоо',
    'nav.favorites': 'Тандалгандар',
    'nav.chat': 'Чаттар',
    'nav.profile': 'Профиль',

    'theme.light': 'Жарык тема',
    'theme.dark': 'Караңгы тема',
    'theme.light.aria': 'Жарык теманы күйгүзүү',
    'theme.dark.aria': 'Караңгы теманы күйгүзүү',

    'auth.login': 'Кирүү',
    'auth.logout': 'Чыгуу',
    'auth.register': 'Катталуу',
    'auth.welcome': 'Кош келиңиз!',
    'auth.welcome.sub': 'Кириңиз же аккаунт түзүңүз',
    'auth.login.tab': 'Кирүү',
    'auth.register.tab': 'Катталуу',
    'auth.username': 'Колдонуучу аты',
    'auth.password': 'Сырсөз',
    'auth.confirm': 'Сырсөздү кайталаңыз',
    'auth.login.btn': 'Кирүү 🚀',
    'auth.register.btn': 'Катталуу 🚀',
    'auth.fill.all': 'Бардык талааларды толтуруңуз',
    'auth.username.len': 'Колдонуучу аты 2-20 белгиден турушу керек',
    'auth.password.len': 'Сырсөз жок дегенде 6 белгиден турушу керек',
    'auth.password.match': 'Сырсөздөр дал келбейт',
    'auth.taken': 'Бул колдонуучу аты мурда эле алынган',
    'auth.register.error': 'Катталууда ката',
    'auth.notfound': 'Колдонуучу табылган жок',
    'auth.wrongpass': 'Сырсөз туура эмес',
    'auth.loggedout': 'Сиз аккаунттан чыктыңыз',
    'auth.logout.confirm.title': 'Аккаунттан чыгуу?',
    'auth.logout.confirm.sub': 'Чыгууну каалайсызбы?',
    'auth.logout.confirm.ok': '🚪 Чыгуу',
    'auth.logout.confirm.cancel': 'Жок',
    'auth.strength.weak': 'Алсыз',
    'auth.strength.medium': 'Орто',
    'auth.strength.strong': 'Күчтүү',

    'search.placeholder': 'Жарыяларды издөө...',
    'search.clear': 'Тазалоо',
    'filter.all': 'Баары',
    'filter.sort': 'Иреттөө:',
    'filter.newest': 'Алгач жаңылары',
    'filter.oldest': 'Алгач эскилери',
    'filter.price.asc': 'Баасы ↑',
    'filter.price.desc': 'Баасы ↓',
    'filter.popular': 'Көрүүлөр боюнча',
    'filter.my': 'Меники',
    'filter.my.title': 'Жеке жарыяларды гана көрсөтүү',
    'filter.price.from': 'Баасынан',
    'filter.price.to': 'Баасына чейин',
    'filter.reset': 'Тазалоо',
    'filter.reset.title': 'Бардык фильтрлерди тазалоо',

    'item.fav.add': 'Тандалгандарга кошулду',
    'item.fav.remove': 'Тандалгандардан алынды',
    'item.fav.add.title': 'Тандалгандарга',
    'item.fav.remove.title': 'Тандалгандардан алуу',
    'item.sold': 'Сатылды',
    'item.free': 'Акысыз',
    'item.currency': 'Сом',
    'item.no.description': 'Сүрөттөмө жок',
    'item.no.contact': 'Көрсөтүлгөн эмес',
    'item.views': 'көрүүлөр',
    'item.seller': 'Сатуучу',
    'item.contact': '📩 Байланышуу',
    'item.description': 'Сүрөттөмө',
    'item.edit': '✏️ Оңдоо',
    'item.delete': '🗑 Өчүрүү',
    'item.restore': '♻️ Калыбына келтирүү',
    'item.sold.toggle': '✅ Сатылды',
    'item.sold.untoggle': '↩️ Сатууга кайтаруу',
    'item.share.copy': 'Шилтеме көчүрүлдү! 🔗',
    'item.share.tg': 'Telegramда бөлүшүү',
    'item.share.wa': 'WhatsAppта бөлүшүү',

    'detail.loading': 'Жарыя жүктөлүүдө...',
    'detail.notfound': 'Жарыя табылган жок',
    'detail.notfound.text': 'Ал өчүрүлгөн болушу мүмкүн',
    'detail.back': '← Башкыга',
    'detail.breadcrumb': 'Башкы',
    'detail.recent': '👁 Акыркы көргөндөр',
    'detail.similar': '📂 Окшош жарыялар',

    'create.title.new': '✨ Жаңы жарыя',
    'create.title.edit': '✏️ Оңдоо',
    'create.sub.new': 'Товарды жайгаштыруу үчүн форманы толтуруңуз',
    'create.sub.edit': 'Жарыянын маалыматтарын өзгөртүү',
    'create.breadcrumb.new': 'Жаңы жарыя',
    'create.breadcrumb.edit': 'Оңдоо',
    'create.btn.publish': '🚀 Жарыялоо',
    'create.btn.save': '💾 Өзгөртүүлөрдү сактоо',
    'create.btn.back': '← Артка',
    'create.label.photo': '📷 Товардын сүрөтү',
    'create.upload.text': 'Сүрөттү тандоо же жылдыруу',
    'create.upload.hint': 'JPG, PNG 2 MB чейин',
    'create.upload.remove': 'Сүрөттү өчүрүү',
    'create.label.title': 'Аталышы',
    'create.title.placeholder': 'Мисалы: iPhone 12 чехол',
    'create.title.hint': '100 белгиге чейин',
    'create.label.desc': 'Сүрөттөмө',
    'create.desc.placeholder': 'Товарды толук сүрөттөңүз: абалы, өлчөмү, түсү...',
    'create.desc.hint': '5000 белгиге чейин',
    'create.label.price': 'Баасы',
    'create.price.placeholder': '0 = акысыз',
    'create.price.hint': 'Эгер акысыз берсеңиз, 0 жазыңыз',
    'create.label.category': 'Категория',
    'create.category.placeholder': 'Категорияны тандаңыз',
    'create.label.contact': 'Байланыш',
    'create.contact.placeholder': 'Telegram, WhatsApp же телефон номери',
    'create.error.title': 'Товардын аталышын жазыңыз',
    'create.error.desc': 'Сүрөттөмө кошуңуз',
    'create.error.price': 'Баасын көрсөтүңүз',
    'create.error.category': 'Категорияны тандаңыз',
    'create.error.contact': 'Байланыш маалыматын көрсөтүңүз',
    'create.error.image': 'Сүрөттү тандаңыз (JPG, PNG)',
    'create.error.filesize': 'Файл өтө чоң (макс. 2 MB)',
    'create.error.notfound': 'Жарыя табылган жок',
    'create.error.permission': 'Сиз бул жарыяны оңдой албайсыз',
    'create.loading.photo': '⏳ Сүрөт жүктөлүүдө...',
    'create.loading.save': '⏳ Сакталууда...',
    'create.success.update': 'Жарыя жаңыртылды! ✅',
    'create.success.create': 'Жарыя түзүлдү! 🎉',
    'create.error.save': 'Сактоодо ката',

    'profile.edit': '✏️ Оңдоо',
    'profile.logout': '🚪 Чыгуу',
    'profile.myitems': 'Менин жарыяларым',
    'profile.tab.active': 'Активдүү',
    'profile.tab.deleted': 'Өчүрүлгөн',
    'profile.loading': 'Жарыялар жүктөлүүдө...',
    'profile.modal.title': 'Профилди оңдоо',
    'profile.modal.sub': 'Өзүңүз жөнүндө маалымат толтуруңуз',
    'profile.label.avatar': 'Профилдин сүрөтү',
    'profile.avatar.upload': '📷 Жүктөө',
    'profile.avatar.remove': '✕ Өчүрүү',
    'profile.label.name': 'Аты',
    'profile.name.placeholder': 'Иван Иванов',
    'profile.label.email': 'Email',
    'profile.email.placeholder': 'your@school.edu',
    'profile.label.bio': 'Өзүм жөнүндө',
    'profile.bio.placeholder': 'Өзүңүз, кызыгууларыңыз, байланыштарыңыз жөнүндө айтыңыз...',
    'profile.label.location': 'Шаар / Мектеп',
    'profile.location.placeholder': 'Мисалы: Бишкек, №70 мектеп',
    'profile.cancel': 'Жок',
    'profile.save': '💾 Сактоо',
    'profile.no.email': 'Email көрсөтүлгөн эмес',
    'profile.member.since': '2026-жылдан бери катышуучу',
    'profile.empty.title': 'Азырынча жарыяңыз жок',
    'profile.empty.text': 'Биринчи жарыяңызды түзүңүз',
    'profile.empty.btn': 'Жарыя түзүү',
    'profile.empty.deleted': 'Өчүрүлгөн жарыялар жок',
    'profile.empty.deleted.text': 'Өчүрүлгөн жарыялар ушул жерде болот',
    'profile.avatar.error': 'Сүрөт 2 MB ашпоого тийиш',
    'profile.saved': 'Профиль жаңыртылды',

    // ─── Chat ───
    'chat.title': 'Билдирүүлөр',
    'chat.loading': 'Жүктөлүүдө...',
    'chat.select': 'Чатты тандаңыз',
    'chat.select.text': 'Билдирүүлөрдү көрүү үчүн сол жактагы диалогду басыңыз',
    'chat.no.conversations': 'Диалогдор жок',
    'chat.no.messages': 'Билдирүүлөр жок',
    'chat.input.placeholder': 'Билдирүү жазыңыз...',
    'chat.send': 'Жиберүү',
    'detail.chat': '💬 Чатка жазуу',

    'fav.title': '♥ Тандалгандар',
    'fav.subtitle': 'Сакталган жарыяларыңыз',
    'fav.empty.title': 'Тандалгандар жок',
    'fav.empty.text': 'Жарыяларды тандалгандарга кошуп, жоготпой сактаңыз',
    'fav.empty.btn': '← Башкыга',

    'empty.notfound': 'Эч нерсе табылган жок',
    'empty.notfound.text': 'Издөөнү же фильтрлерди өзгөртүп көрүңүз',
    'empty.noitems': 'Жарыялар азырынча жок',
    'empty.noitems.text': 'Биринчи болуп жарыялаңыз!',
    'empty.create': 'Жарыя түзүү',

    'hero.title': 'Кош келиңиз',
    'hero.sub': 'Курбуларыңыз менен буюмдарды сатып, сатып, алмаштырыңыз. Окуу китептери, гаджеттер, кийимдер жана башкалар!',
    'hero.cta': 'Жарыялоо',

    'breadcrumb.home': 'Башкы',

    'footer.text': '🎒 School Shop © 2026 — ❤️ менен жасалды',
    'footer.export': '💾 Экспорт',
    'footer.export.title': 'Резервдик көчүрмөнү жүктөө',

    'scroll.top': 'Жогору',

    'time.justnow': 'Азыр',
    'time.minutes': 'мүн. мурун',
    'time.hours': 'саат мурун',
    'time.days': 'күн мурун',

    'validate.title.len': 'Аталышы жок дегенде 3 белгиден турушу керек',
    'validate.desc.len': 'Сүрөттөмө 5000 белгиден ашпоого тийиш',

    'delete.title': 'Жарыяны өчүрүү?',
    'delete.sub': 'Жарыяны калыбына келтирүүгө болот',
    'delete.cancel': 'Жок',
    'delete.confirm': '🗑 Өчүрүү',

    'toast.copied': 'Шилтеме көчүрүлдү! 🔗',
    'toast.deleted': 'Жарыя жашырылды. Аны калыбына келтирүүгө болот ♻️',
    'toast.restored': 'Жарыя калыбына келтирилди! ✅',
    'toast.sold': '✅ Жарыя сатылган деп белгиленди',
    'toast.active': '↩️ Жарыя кайра сатууда',
    'toast.load.error': 'Маалыматтарды жүктөөдө ката',
    'toast.save.error': 'Маалыматтарды сактоодо ката',
    'toast.version.error': 'Версиялар конфликти — баракты жаңыртыңыз',
    'toast.photo.error': 'Сүрөттү жүктөөдө ката',
    'toast.update.error': 'Жаңыртууда ката',
    'toast.delete.error': 'Өчүрүүдө ката',
    'toast.restore.error': 'Калыбына келтирүүдө ката',
    'toast.status.error': 'Статусту жаңыртууда ката',
    'toast.create.error': 'Жарыя түзүүдө ката',

    'items.one': 'жарыя',
    'items.few': 'жарыя',
    'items.many': 'жарыя',
    'items.found': 'Табылды',
    'items.found.end': '',
    'items.loading': 'Жүктөлүүдө...',

    'cat.учебники': 'Окуу китептери',
    'cat.электроника': 'Электроника',
    'cat.одежда': 'Кийимдер',
    'cat.другое': 'Башка',

    'lang.ru': 'Русский',
    'lang.kg': 'Кыргызча',
    'lang.en': 'English',
  },

  en: {
    'nav.home': 'Home',
    'nav.create': 'Create',
    'nav.favorites': 'Favorites',
    'nav.chat': 'Chats',
    'nav.profile': 'Profile',

    'theme.light': 'Light theme',
    'theme.dark': 'Dark theme',
    'theme.light.aria': 'Enable light theme',
    'theme.dark.aria': 'Enable dark theme',

    'auth.login': 'Log In',
    'auth.logout': 'Log Out',
    'auth.register': 'Register',
    'auth.welcome': 'Welcome!',
    'auth.welcome.sub': 'Log in or create an account',
    'auth.login.tab': 'Log In',
    'auth.register.tab': 'Register',
    'auth.username': 'Username',
    'auth.password': 'Password',
    'auth.confirm': 'Confirm password',
    'auth.login.btn': 'Log In 🚀',
    'auth.register.btn': 'Register 🚀',
    'auth.fill.all': 'Fill in all fields',
    'auth.username.len': 'Username must be 2-20 characters',
    'auth.password.len': 'Password must be at least 6 characters',
    'auth.password.match': 'Passwords do not match',
    'auth.taken': 'This username is already taken',
    'auth.register.error': 'Registration error',
    'auth.notfound': 'User not found',
    'auth.wrongpass': 'Wrong password',
    'auth.loggedout': 'You have logged out',
    'auth.logout.confirm.title': 'Log out?',
    'auth.logout.confirm.sub': 'Are you sure you want to log out?',
    'auth.logout.confirm.ok': '🚪 Log Out',
    'auth.logout.confirm.cancel': 'Cancel',
    'auth.strength.weak': 'Weak',
    'auth.strength.medium': 'Medium',
    'auth.strength.strong': 'Strong',

    'search.placeholder': 'Search listings...',
    'search.clear': 'Clear',
    'filter.all': 'All',
    'filter.sort': 'Sort:',
    'filter.newest': 'Newest first',
    'filter.oldest': 'Oldest first',
    'filter.price.asc': 'Price ↑',
    'filter.price.desc': 'Price ↓',
    'filter.popular': 'Most viewed',
    'filter.my': 'Mine',
    'filter.my.title': 'Show only my listings',
    'filter.price.from': 'Price from',
    'filter.price.to': 'Price to',
    'filter.reset': 'Reset',
    'filter.reset.title': 'Reset all filters',

    'item.fav.add': 'Added to favorites',
    'item.fav.remove': 'Removed from favorites',
    'item.fav.add.title': 'Add to favorites',
    'item.fav.remove.title': 'Remove from favorites',
    'item.sold': 'Sold',
    'item.free': 'Free',
    'item.currency': 'Som',
    'item.no.description': 'No description',
    'item.no.contact': 'Not specified',
    'item.views': 'views',
    'item.seller': 'Seller',
    'item.contact': '📩 Contact',
    'item.description': 'Description',
    'item.edit': '✏️ Edit',
    'item.delete': '🗑 Delete',
    'item.restore': '♻️ Restore',
    'item.sold.toggle': '✅ Sold',
    'item.sold.untoggle': '↩️ Mark as active',
    'item.share.copy': 'Link copied! 🔗',
    'item.share.tg': 'Share on Telegram',
    'item.share.wa': 'Share on WhatsApp',

    'detail.loading': 'Loading listing...',
    'detail.notfound': 'Listing not found',
    'detail.notfound.text': 'It may have been deleted',
    'detail.back': '← Back to Home',
    'detail.breadcrumb': 'Home',
    'detail.recent': '👁 Recently viewed',
    'detail.similar': '📂 Similar listings',

    'create.title.new': '✨ New Listing',
    'create.title.edit': '✏️ Edit Listing',
    'create.sub.new': 'Fill in the form to post your item',
    'create.sub.edit': 'Update your listing details',
    'create.breadcrumb.new': 'New Listing',
    'create.breadcrumb.edit': 'Editing',
    'create.btn.publish': '🚀 Publish',
    'create.btn.save': '💾 Save Changes',
    'create.btn.back': '← Back',
    'create.label.photo': '📷 Photo',
    'create.upload.text': 'Click or drag a photo',
    'create.upload.hint': 'JPG, PNG up to 2 MB',
    'create.upload.remove': 'Remove photo',
    'create.label.title': 'Title',
    'create.title.placeholder': 'e.g. iPhone 12 case',
    'create.title.hint': 'Up to 100 characters',
    'create.label.desc': 'Description',
    'create.desc.placeholder': 'Describe the item: condition, size, color...',
    'create.desc.hint': 'Up to 5000 characters',
    'create.label.price': 'Price',
    'create.price.placeholder': '0 = free',
    'create.price.hint': 'Enter 0 if giving away for free',
    'create.label.category': 'Category',
    'create.category.placeholder': 'Select category',
    'create.label.contact': 'Contact',
    'create.contact.placeholder': 'Telegram, WhatsApp or phone number',
    'create.error.title': 'Enter item title',
    'create.error.desc': 'Add a description',
    'create.error.price': 'Set a price',
    'create.error.category': 'Select a category',
    'create.error.contact': 'Provide contact info',
    'create.error.image': 'Select an image (JPG, PNG)',
    'create.error.filesize': 'File too large (max 2 MB)',
    'create.error.notfound': 'Listing not found',
    'create.error.permission': 'You cannot edit this listing',
    'create.loading.photo': '⏳ Uploading photo...',
    'create.loading.save': '⏳ Saving...',
    'create.success.update': 'Listing updated! ✅',
    'create.success.create': 'Listing created! 🎉',
    'create.error.save': 'Error saving',

    'profile.edit': '✏️ Edit',
    'profile.logout': '🚪 Log Out',
    'profile.myitems': 'My Listings',
    'profile.tab.active': 'Active',
    'profile.tab.deleted': 'Deleted',
    'profile.loading': 'Loading listings...',
    'profile.modal.title': 'Edit Profile',
    'profile.modal.sub': 'Fill in your information',
    'profile.label.avatar': 'Profile photo',
    'profile.avatar.upload': '📷 Upload',
    'profile.avatar.remove': '✕ Remove',
    'profile.label.name': 'Name',
    'profile.name.placeholder': 'John Doe',
    'profile.label.email': 'Email',
    'profile.email.placeholder': 'your@school.edu',
    'profile.label.bio': 'About me',
    'profile.bio.placeholder': 'Tell about yourself, hobbies, contacts...',
    'profile.label.location': 'City / School',
    'profile.location.placeholder': 'e.g. Bishkek, School #70',
    'profile.cancel': 'Cancel',
    'profile.save': '💾 Save',
    'profile.no.email': 'Email not set',
    'profile.member.since': 'Member since 2026',
    'profile.empty.title': 'You have no listings yet',
    'profile.empty.text': 'Create your first listing',
    'profile.empty.btn': 'Create listing',
    'profile.empty.deleted': 'No deleted listings',
    'profile.empty.deleted.text': 'Deleted listings will appear here',
    'profile.avatar.error': 'Photo must be under 2 MB',
    'profile.saved': 'Profile updated',

    // ─── Chat ───
    'chat.title': 'Messages',
    'chat.loading': 'Loading...',
    'chat.select': 'Select a chat',
    'chat.select.text': 'Click a conversation on the left to view messages',
    'chat.no.conversations': 'No conversations',
    'chat.no.messages': 'No messages',
    'chat.input.placeholder': 'Write a message...',
    'chat.send': 'Send',
    'detail.chat': '💬 Write in chat',

    'fav.title': '♥ Favorites',
    'fav.subtitle': 'Your saved listings',
    'fav.empty.title': 'No favorites yet',
    'fav.empty.text': 'Add listings to favorites to keep them',
    'fav.empty.btn': '← Back to Home',

    'empty.notfound': 'Nothing found',
    'empty.notfound.text': 'Try changing the search or filters',
    'empty.noitems': 'No listings yet',
    'empty.noitems.text': 'Be the first to post a listing!',
    'empty.create': 'Create listing',

    'hero.title': 'Welcome to',
    'hero.sub': 'Buy, sell, and trade items with classmates. Textbooks, gadgets, clothes, and more!',
    'hero.cta': 'Post a Listing',

    'breadcrumb.home': 'Home',

    'footer.text': '🎒 School Shop © 2026 — Made with ❤️',
    'footer.export': '💾 Export',
    'footer.export.title': 'Download backup',

    'scroll.top': 'Scroll to top',

    'time.justnow': 'Just now',
    'time.minutes': 'min. ago',
    'time.hours': 'h ago',
    'time.days': 'd ago',

    'validate.title.len': 'Title must be at least 3 characters',
    'validate.desc.len': 'Description cannot exceed 5000 characters',

    'delete.title': 'Delete listing?',
    'delete.sub': 'The listing can be restored',
    'delete.cancel': 'Cancel',
    'delete.confirm': '🗑 Delete',

    'toast.copied': 'Link copied! 🔗',
    'toast.deleted': 'Listing hidden. It can be restored ♻️',
    'toast.restored': 'Listing restored! ✅',
    'toast.sold': '✅ Listing marked as sold',
    'toast.active': '↩️ Listing is back on sale',
    'toast.load.error': 'Error loading data',
    'toast.save.error': 'Error saving data',
    'toast.version.error': 'Version conflict — refresh the page',
    'toast.photo.error': 'Error uploading photo',
    'toast.update.error': 'Error updating',
    'toast.delete.error': 'Error deleting',
    'toast.restore.error': 'Error restoring',
    'toast.status.error': 'Error updating status',
    'toast.create.error': 'Error creating listing',

    'items.one': 'listing',
    'items.few': 'listings',
    'items.many': 'listings',
    'items.found': 'Found',
    'items.found.end': '',
    'items.loading': 'Loading...',

    'cat.учебники': 'Textbooks',
    'cat.электроника': 'Electronics',
    'cat.одежда': 'Clothing',
    'cat.другое': 'Other',

    'lang.ru': 'Русский',
    'lang.kg': 'Кыргызча',
    'lang.en': 'English',

    'nav.logout': 'Sign out',
    'nav.back': '← Back',
    'auth.subtitle': 'Sign in or create an account',
    'auth.password.confirm': 'Confirm password',
    'filter.myads': 'Mine',
    'sort.newest': 'Newest first',
    'sort.oldest': 'Oldest first',
    'sort.price.asc': 'Price ↑',
    'sort.price.desc': 'Price ↓',
    'sort.views': 'Most viewed',
    'footer.made': 'Made with ❤️',
    'hero.welcome': 'Welcome to',
    'hero.subtitle': 'Buy, sell, and trade items with classmates. Textbooks, gadgets, clothes, and more!',
    'favorites.subtitle': 'Your saved listings',
    'favorites.empty.title': 'No favorites yet',
    'favorites.empty.text': 'Add listings to favorites to keep them',
    'detail.breadcrumb': 'Listing',
    'detail.description': 'Description',
    'detail.seller': 'Seller',
    'detail.contact': '📩 Contact',
    'detail.views': 'views',
    'detail.recently': '👁 Recently viewed',
    'detail.share.link': 'Copy link',
    'detail.share.tg': 'Share via Telegram',
    'detail.share.wa': 'Share via WhatsApp',
    'detail.delete.title': 'Delete listing?',
    'detail.delete.sub': 'The listing can be restored',
    'item.image.alt': 'Product photo',
    'create.new': 'New listing',
    'create.photo.label': '📷 Product photo',
    'create.photo.click': 'Click',
    'create.photo.drag': 'or drag photo here',
    'create.photo.hint': 'JPG, PNG up to 2 MB',
    'create.photo.remove': 'Remove photo',
    'create.title.label': 'Title',
    'create.title.error': 'Enter a title',
    'create.desc.label': 'Description',
    'create.desc.error': 'Add a description',
    'create.price.label': 'Price',
    'create.price.error': 'Enter a price',
    'create.cat.label': 'Category',
    'create.cat.error': 'Select a category',
    'create.cat.placeholder': 'Select a category',
    'create.contact.label': 'Contact',
    'create.contact.error': 'Enter a contact',
    'create.btn.submit': '🚀 Publish',
    'profile.edit.title': 'Edit profile',
    'profile.edit.sub': 'Fill in your information',
    'profile.edit.avatar': 'Profile photo',
    'profile.edit.upload': '📷 Upload',
    'profile.edit.remove': '✕ Remove',
    'profile.edit.name': 'Name',
    'profile.edit.name.placeholder': 'John Doe',
    'profile.edit.email': 'Email',
    'profile.edit.email.placeholder': 'your@school.edu',
    'profile.edit.bio': 'About me',
    'profile.edit.bio.placeholder': 'Tell about yourself...',
    'profile.edit.location': 'City / School',
    'profile.edit.location.placeholder': 'e.g. Bishkek, School #70',
    'profile.edit.save': '💾 Save',
    'profile.edit.username': 'Username',
  }
};

const Lang = {
  STORAGE_KEY: 'marketplace_lang',
  _current: null,

  get current() {
    if (!this._current) {
      const saved = localStorage.getItem(this.STORAGE_KEY);
      if (LANGUAGES.some(l => l.code === saved)) {
        this._current = saved;
      } else {
        this._current = 'ru';
      }
    }
    return this._current;
  },

  set(code) {
    if (!LANGUAGES.some(l => l.code === code)) return;
    this._current = code;
    localStorage.setItem(this.STORAGE_KEY, code);
    document.documentElement.lang = code;
    document.documentElement.setAttribute('data-lang', code);
  },

  t(key) {
    return LANGS[this.current]?.[key] ?? LANGS.ru[key] ?? key;
  },

  init() {
    const code = this.current;
    document.documentElement.lang = code;
    document.documentElement.setAttribute('data-lang', code);
  },

  translatePage() {
    document.querySelectorAll('[data-i18n]').forEach(el => {
      const key = el.getAttribute('data-i18n');
      el.textContent = this.t(key);
    });
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
      const key = el.getAttribute('data-i18n-placeholder');
      el.placeholder = this.t(key);
    });
    document.querySelectorAll('[data-i18n-title]').forEach(el => {
      const key = el.getAttribute('data-i18n-title');
      el.title = this.t(key);
    });
    document.querySelectorAll('[data-i18n-aria]').forEach(el => {
      const key = el.getAttribute('data-i18n-aria');
      el.setAttribute('aria-label', this.t(key));
    });
    document.querySelectorAll('[data-i18n-alt]').forEach(el => {
      const key = el.getAttribute('data-i18n-alt');
      el.alt = this.t(key);
    });
  },

  onChange(fn) {
    this._cbs = this._cbs || [];
    this._cbs.push(fn);
  },

  _fireChange() {
    if (this._cbs) this._cbs.forEach(fn => fn());
  }
};

const onLangChange = (code) => {
  Lang.set(code);
  Lang.translatePage();
  if (typeof Theme !== 'undefined') {
    Theme.apply(Theme.get());
  }
  Lang._fireChange();
};

document.addEventListener('DOMContentLoaded', () => {
  Lang.init();
  Lang.translatePage();

  document.querySelectorAll('#lang-select, #lang-select-mobile').forEach(sel => {
    sel.value = Lang.current;
    sel.addEventListener('change', e => onLangChange(e.target.value));
  });
});
